export const siteConfig = {
  name: "Diksha Ghanshani",
  description:
    "Portfolio of Diksha Ghanshani, a product and UX designer creating AI-first products, human-centered digital experiences, healthcare innovation, design systems, and research-led product strategy.",
  url: "https://dikshaghanshani.com",
  locale: "en_IN",
  language: "en-IN",
  ogImage: "/og.png",
  keywords: [
    "Diksha Ghanshani",
    "Diksha Ghanshani portfolio",
    "product designer portfolio",
    "UX designer portfolio",
    "UI UX designer",
    "AI product designer",
    "AI UX designer",
    "human centered AI design",
    "product design portfolio India",
    "UX research portfolio",
    "user experience designer",
    "interaction designer",
    "digital product designer",
    "design strategy",
    "product strategy",
    "experience design",
    "human centered design",
    "design systems",
    "Figma designer",
    "healthcare UX design",
    "healthcare product design",
    "Type 1 Diabetes design",
    "sustainable product design",
    "NID designer",
    "IISc healthcare innovation",
    "Intuit UX designer",
    "Tata 1mg design",
    "case study portfolio",
  ],
  contact: {
    phone: "",
    email: "dikshaghanshani97@gmail.com",
  },
  address: {
    street: "",
    city: "",
    state: "",
    postalCode: "",
    country: "IN",
  },
  socials: {
    facebook: "",
    instagram: "",
    behance: "https://www.behance.net/dikshaghan7cec",
    linkedin: "https://www.linkedin.com/in/dikshaghanshani/",
  },
};

export const siteRoutes = [
  {
    path: "/",
    label: "Home",
    title: "Diksha Ghanshani - Product Designer ",
    description: siteConfig.description,
    priority: 1,
  },
  {
    path: "/about",
    label: "About",
    title: "About Diksha Ghanshani - Product & UX Designer",
    description:
      "Learn about Diksha Ghanshani's design journey across AI-first products, healthcare innovation, sustainable product thinking, user research, and human-centered experience design.",
    priority: 0.8,
  },
  {
    path: "/playground",
    label: "Playground",
    title: "Design Playground - Visual Experiments & Explorations",
    description:
      "Explore Diksha Ghanshani's design playground, a collection of visual experiments, creative explorations, product ideas, interface studies, and studio-style design work.",
    priority: 0.7,
  },
  {
    path: "/contact",
    label: "Contact",
    title: "Contact Diksha Ghanshani - Product Design Collaboration",
    description:
      "Contact Diksha Ghanshani for product design, UX strategy, AI product design, healthcare UX, design research, and thoughtful digital experience collaborations.",
    priority: 0.6,
  },
];
